exit when error

diff --git a/.github/workflows/pr-approved.yml b/.github/workflows/pr-approved.yml
--- a/.github/workflows/pr-approved.yml
+++ b/.github/workflows/pr-approved.yml
@@ -15,7 +15,9 @@ jobs:
     steps:
       - name: check fork
         if: github.event.pull_request.head.repo.full_name != github.repository
-        run: echo "::error::Forks are not supported"
+        run: |
+          echo "::error::Forks are not supported"
+          exit 1
 
   echo-state:
     needs: [set-state]
